In [18]:
!pip install nltk


In [19]:
import pandas as pd

In [20]:
df = pd.read_csv('papers.csv')

In [21]:
df.head(10)

id  year                                              title event_type  \
0     1  1987  Self-Organization of Associative Database and ...        NaN   
1    10  1987  A Mean Field Theory of Layer IV of Visual Cort...        NaN   
2   100  1988  Storing Covariance by the Associative Long-Ter...        NaN   
3  1000  1994  Bayesian Query Construction for Neural Network...        NaN   
4  1001  1994  Neural Network Ensembles, Cross Validation, an...        NaN   
5  1002  1994  Using a neural net to instantiate a deformable...        NaN   
6  1003  1994           Plasticity-Mediated Competitive Learning        NaN   
7  1004  1994  ICEG Morphology Classification using an Analog...        NaN   
8  1005  1994  Real-Time Control of a Tokamak Plasma Using Ne...        NaN   
9  1006  1994  Pulsestream Synapses with Non-Volatile Analogu...        NaN   

                                            pdf_name          abstract  \
0  1-self-organization-of-associative-database-an...  Abstract Missing   
1  10-a-mean-field-theory-of-layer-iv-of-visual-c...  Abstract Missing   
2  100-storing-covariance-by-the-associative-long...  Abstract Missing   
3  1000-bayesian-query-construction-for-neural-ne...  Abstract Missing   
4  1001-neural-network-ensembles-cross-validation...  Abstract Missing   
5  1002-using-a-neural-net-to-instantiate-a-defor...  Abstract Missing   
6  1003-plasticity-mediated-competitive-learning.pdf  Abstract Missing   
7  1004-iceg-morphology-classification-using-an-a...  Abstract Missing   
8  1005-real-time-control-of-a-tokamak-plasma-usi...  Abstract Missing   
9  1006-pulsestream-synapses-with-non-volatile-an...  Abstract Missing   

                                          paper_text  
0  767\n\nSELF-ORGANIZATION OF ASSOCIATIVE DATABA...  
1  683\n\nA MEAN FIELD THEORY OF LAYER IV OF VISU...  
2  394\n\nSTORING COVARIANCE BY THE ASSOCIATIVE\n...  
3  Bayesian Query Construction for Neural\nNetwor...  
4  Neural Network Ensembles, Cross\nValidation, a...  
5  U sing a neural net to instantiate a\ndeformab...  
6  Plasticity-Mediated Competitive Learning\n\nTe...  
7  ICEG Morphology Classification using an\nAnalo...  
8  Real-Time Control of a Tokamak Plasma\nUsing N...  
9  Real-Time Control of a Tokamak Plasma\nUsing N...

In [22]:
df.shape

(7241, 7)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7241 entries, 0 to 7240
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   id          7241 non-null   int64 
 1   year        7241 non-null   int64 
 2   title       7241 non-null   object
 3   event_type  2422 non-null   object
 4   pdf_name    7241 non-null   object
 5   abstract    7241 non-null   object
 6   paper_text  7241 non-null   object
dtypes: int64(2), object(5)
memory usage: 396.1+ KB


In [24]:
df.isna().sum()


id               0
year             0
title            0
event_type    4819
pdf_name         0
abstract         0
paper_text       0
dtype: int64

In [25]:
df.update(df[['event_type']].fillna('Unknown'))


In [26]:
df.isna().sum()

id            0
year          0
title         0
event_type    0
pdf_name      0
abstract      0
paper_text    0
dtype: int64

In [27]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [28]:

nltk.download('stopwords')


[nltk_data] Downloading package stopwords to C:\Users\Avash
[nltk_data]     Dahal\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [29]:
stop_words = set(stopwords.words("english")) 
print(stop_words)


{'yourselves', 'doesn', 'his', 'through', "wasn't", "needn't", 'she', 'once', 'had', 'out', 'was', 'of', 'as', 'again', 'ours', 'can', 'no', "isn't", 'shan', 'after', 'those', "mightn't", 'to', 'here', 'where', 'should', 'll', 'o', "don't", "won't", 'you', 'didn', 'into', 'my', 'they', 'it', 'be', 'now', 'ma', 'don', "doesn't", 'on', 'than', "hadn't", 'such', 'from', "aren't", 'while', 'own', 'a', 'ourselves', 'does', 'very', 'wasn', 'aren', 'down', 'up', 'over', "haven't", 'me', 'am', 'm', "you're", 'other', 'above', 'doing', 'same', 'i', 'hers', 'and', 'when', 'few', 'been', 'or', 'nor', 'about', 'herself', 'there', 'all', 'hadn', 'him', 'so', 'haven', 'mustn', 'at', 'the', 'her', 'under', 'these', 't', 'against', 'will', 'both', 'have', 'theirs', 'yours', 'wouldn', 'in', "she's", 'having', 'has', 'its', 'did', 'during', 're', "wouldn't", 'our', 'myself', 'why', "should've", 'then', 'is', 'who', 'mightn', 'more', "mustn't", 'off', "shan't", 'if', 'too', 's', 'ain', 'we', 'how', 'an',

In [30]:
#custom stopwords can also be created 
new_words = [
    "fig", "figure", "image", "sample", "using",
    "show", "result", "large", "also", "one", "two",
    "three", "four", "five", "seven", "eight", "nine",
    "data", "analysis", "example", "method", "table",
    "experiment", "study", "observed", "calculated",
    "reported", "value", "values", "different",
    "approach", "various", "similar", "significant",
    "obtained", "considered", "indicated", "presented",
    "described", "number", "respectively"
]
stop_words=list(stop_words.union(new_words))

In [35]:
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to C:\Users\Avash
[nltk_data]     Dahal\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


True

In [46]:
#Text Preprocessing

def preprocessing_text(text):
    clean_text = text.lower()  # Converting to lowercase
    clean_text = re.sub(r'<.*?>', ' ', clean_text)  # Removing tags
    clean_text = re.sub(r'[^a-zA-Z\s]', '', clean_text)    # Removing numbers
    clean_text = word_tokenize(clean_text)
    clean_text=[word for word in clean_text if word not in stop_words]
    stemming= PorterStemmer()
    clean_text=[stemming.stem(word) for word in clean_text]
    return ' '.join(clean_text)

In [48]:
preprocessing_text("This moving loving  is a text <h1> <p1>I need ankle brackets removed 1 2 4 5432233 </p1> </h1>")


'move love text need ankl bracket remov'

In [49]:
docs= df['paper_text'].apply(lambda x:preprocessing_text(x))

In [51]:
docs[0]

'selforgan associ databas applic hisashi suzuki suguru arimoto osaka univers toyonaka osaka japan abstract effici selforgan associ databas propos togeth applic robot eyesight system propos databas associ input output first half part discuss algorithm selforgan propos aspect hardwar produc new style neural network latter half part applic handwritten letter recognit autonom mobil robot system demonstr introduct let map f x given x finit infinit set anoth finit infinit set learn machin observ set pair x sampl randomli x x x x mean cartesian product x comput estim j x f make small estim error measur usual say faster decreas estim error increas sampl better learn machin howev express perform incomplet sinc lack consider candid j j assum preliminarili find good learn machin clarifi concept let us discuss type learn machin let us advanc understand selforgan associ databas paramet type ordinari type learn machin assum equat relat xs ys paramet indefinit name structur f equival defin implicitli

In [52]:
#Count Vectorizer 

In [58]:
from sklearn.feature_extraction.text import CountVectorizer

# Sample text data
documents = [
    "I love programming programming programming in Python",
    "Python is great great for data science",
    "I love data science and machine learning programming"
]

# Create CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the documents
X = vectorizer.fit_transform(documents)

# Convert to array for better readability
print(X.toarray())

# Display the feature names (words)
print(vectorizer.get_feature_names_out())


[[0 0 0 0 1 0 0 1 0 3 1 0]
 [0 1 1 2 0 1 0 0 0 0 1 1]
 [1 1 0 0 0 0 1 1 1 1 0 1]]
['and' 'data' 'for' 'great' 'in' 'is' 'learning' 'love' 'machine'
 'programming' 'python' 'science']


In [ ]:
'''How CountVectorizer Works
It tokenizes the text (splits it into words).
It creates a vocabulary of all unique words in the dataset.
It represents each document as a vector where each entry corresponds to the count of a specific word in that document.'''


In [68]:
'''
max_df=0.9: Ignores terms that appear in more than 90% of the documents, treating them as too common (like stop words).
max_features=7000: Limits the vocabulary size to the 7,000 most frequently occurring words.
ngram_range=(1,3): Extracts unigrams (single words), bigrams (two-word combinations), and trigrams (three-word combinations).
'''

'\nmax_df=0.9: Ignores terms that appear in more than 90% of the documents, treating them as too common (like stop words).\nmax_features=7000: Limits the vocabulary size to the 7,000 most frequently occurring words.\nngram_range=(1,3): Extracts unigrams (single words), bigrams (two-word combinations), and trigrams (three-word combinations).\n'

In [61]:
cv= CountVectorizer(max_df=0.9,max_features=7000,ngram_range=(1,3))
word_count_vectors=cv.fit_transform(docs)

In [62]:
word_count_vectors

<7241x7000 sparse matrix of type '<class 'numpy.int64'>'
	with 5070690 stored elements in Compressed Sparse Row format>

In [66]:
#TfidfTransformer
'''
CountVectorizer extracts word counts.
TfidfTransformer converts counts into TF-IDF values.
High TF-IDF score → Important word in that document.
Low TF-IDF score → Common word across documents.
'''

'''
smooth_idf=True: This smoothing prevents division by zero when a term is not present in any document.
use_idf = True: give highest value to less accuring words (keywords)
'''

'\nsmooth_idf=True: This smoothing prevents division by zero when a term is not present in any document.\nuse_idf = True: give highest value to less accuring words (keywords)\n'

In [64]:
from sklearn.feature_extraction.text import TfidfTransformer

In [69]:
tfidf_transformer= TfidfTransformer(smooth_idf=True,use_idf=True)
tfidf_transformer=tfidf_transformer.fit(word_count_vectors)

In [70]:
#Now to get keywords
''' Get features names
word counts for user docs 
sorting sparse matrix conditions
extracting top 10 keywords'''

In [78]:
feature_names=cv.get_feature_names_out()

In [89]:
def get_keywords(index,docs,topNum=10):
    #we get words count and it's importance
    docs_words_count= tfidf_transformer.transform(cv.transform([docs[index]]))
    #sorting sparse matrix
    docs_words_count=docs_words_count.tocoo()
    tuples=zip(docs_words_count.col,docs_words_count.data)
    sorted_items= sorted(tuples,key= lambda x : (x[1],x[0]),reverse=True)
    #getting top 10 keywords
    sorted_items=sorted_items[:topNum]
    score_vals=[]
    feature_vals=[]
    for index,score in sorted_items:
        score_vals.append(round(score,3))
        feature_vals.append(feature_names[index])
    #Make a dictionary to store result
    results= {}
    for index in range(len(feature_vals)):
        results[feature_vals[index]]=score_vals[index]
    return results
    
    

In [92]:

def print_keywords(index,keywords,df):
    print("\n======Title======")
    print(df['title'][index])
    print("\n=====abstract=====")
    print(df['abstract'][index])
    print('\n=====Keywords====')
    for k in keywords:
        print(k,keywords[k])

index=4495
keywords =get_keywords(index,docs)
print_keywords(index,keywords,df)



======Title======
Integrated Non-Factorized Variational Inference

=====abstract=====
We present a non-factorized variational method for full posterior inference in Bayesian hierarchical models,  with the goal of capturing the posterior variable dependencies via efficient and possibly parallel computation. Our approach unifies the integrated nested Laplace approximation (INLA) under the variational framework. The proposed method is applicable in more challenging scenarios than typically assumed by INLA,  such as Bayesian Lasso,  which is characterized by the non-differentiability of the $\ell_{1}$ norm arising from independent Laplace priors. We derive an upper bound for the Kullback-Leibler divergence,  which yields a fast closed-form solution via decoupled optimization. Our method is a reliable analytic alternative to Markov chain Monte Carlo (MCMC), and it results in a tighter evidence lower bound than that of mean-field variational Bayes (VB) method.

=====Keywords====
vb 0.363
po

In [93]:
import pickle
pickle.dump(cv, open('count_vector.pkl', 'wb'))
pickle.dump(tfidf_transformer, open('tfidf_transformer.pkl', 'wb'))
pickle.dump(feature_names, open('feature_names.pkl', 'wb'))